#!/bin/bash

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	woman="man" \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	ffmpeg="ffmpeg -hide_banner" \
	hyfetch="hyfetch --ascii-file $HOME/src/ascii/arch"\
	walter="wal -nest --preview | tail -3 | head -2" \
	fzwal="fzwal; xdotool key super+shift+r;setbg" \
	fzwall="command fzwal -l; xdotool key super+shift+r;setbg" \
	Xephyr="Xephyr :1 -resizeable"\
	yt-playlist="yt-dlp --add-metadata --ignore-errors --format bestaudio --extract-audio --audio-format mp3 --audio-quality 160K --yes-playlist --output '$HOME/media/music_download/%(playlist)s/%(title)s.%(ext)s'"\
	yt-single="yt-dlp --ignore-errors --format bestaudio --extract-audio --audio-format mp3 --audio-quality 160K --output '$HOME/media/music_download/title)s.%(ext)s'"\
	yt-chapters="yt-dlp --add-metadata --ignore-errors --format bestaudio --extract-audio --audio-format mp3 --audio-quality 160K --split-chapters --output 'chapter:$HOME/media/music_download/%(title)s/%(section_title)s.%(ext)s'"\
	# yt="youtube-dl --add-metadata -i" \
	# yta="yt -x -f bestaudio/best" \

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# Git aliases
alias \
	gs="git status"
