#!/bin/bash

# profile file. Runs on login. Environmental variables are set here.

# If you don't plan on reverting to bash, you can remove the link in ~/.profile
# to clean up.

# Adds `~/.local/bin` to $PATH
export PATH="$(du "$HOME/.local/bin" | cut -f2 | paste -sd ':'):$PATH"
# Adds `~/.local/share/bin` to $PATH
export PATH="$(du "$HOME/.local/share/bin" | cut -f2 | paste -sd ':'):$PATH"
export PATH="$PATH:$(go env GOPATH)/bin"

export TERM=xterm-256color

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"

export SUDO_ASKPASS="$HOME/.local/bin/dmenupass"
export SSH_ASKPASS="$HOME/.local/bin/dmenupass"
export SSH_ASKPASS_REQUIRE=force
export LESS=-R
export LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"
export LESS_TERMCAP_md="$(printf '%b' '[1;36m')"
export LESS_TERMCAP_me="$(printf '%b' '[0m')"
export LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"
export LESS_TERMCAP_se="$(printf '%b' '[0m')"
export LESS_TERMCAP_us="$(printf '%b' '[1;32m')"
export LESS_TERMCAP_ue="$(printf '%b' '[0m')"
export LESSOPEN="| /usr/bin/highlight -O ansi %s 2>/dev/null"

export LANG=C
export LC_CTYPE="en_US.UTF-8"
export LC_NUMERIC="en_US.UTF-8"
export LC_TIME="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LC_MONETARY="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export LC_PAPER="en_US.UTF-8"
export LC_NAME="en_US.UTF-8"
export LC_ADDRESS="en_US.UTF-8"
export LC_TELEPHONE="en_US.UTF-8"
export LC_MEASUREMENT="en_US.UTF-8"
export LC_IDENTIFICATION="en_US.UTF-8"
export LC_ALL=

[ -f $XDG_CONFIG_HOME/shell/shortcutrc ] && $XDG_CONFIG_HOME/shell/shortcutrc >/dev/null 2>&1 &
[ -f $XDG_CONFIG_HOME/shell/aliasrc ] && $XDG_CONFIG_HOME/shell/aliasrc >/dev/null 2>&1 &

# Some aliases
alias dotfiles="/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"\
fzwal="fzwal; xdotool key super+shift+r;setbg" \

# Switch escape and caps if tty and no passwd required:
sudo -n loadkeys ${XDG_DATA_HOME:-$HOME/.config}shell/ttymaps.kmap 2>/dev/null
# source your own profile or add to this file
[ -f $XDG_CONFIG_HOME/shell/myprofile ] && source "$XDG_CONFIG_HOME/shell/myprofile"
