#!/bin/bash
# vim: filetype=sh
alias \
cf="cd $HOME/.config && ls -a" \
cfx="$EDITOR $HOME/.config/x11/xresources_template" \
cfv="cd $HOME/.config/nvim; $EDITOR init.lua; cd -" \
cfz="$EDITOR $HOME/.config/zsh/.zshrc" \
cfa="$EDITOR $HOME/.config/shell/aliasrc" \
cfp="$EDITOR $HOME/.config/shell/profile" \
cfwm="cd $HOME/src/env/chadwm; $EDITOR config.def.h; cd -" \
cfs="$EDITOR $HOME/.config/shell/shortcutrc" \
cfstart="$EDITOR $HOME/.local/share/dwm/autostart.sh" \
cfbar="$EDITOR $HOME/.local/bin/bar.sh" \
cfwal="$EDITOR $HOME/.config/wal/postrun" \
cfdots="$EDITOR $HOME/.local/bin/dotfiles-add" \
