#!/bin/sh

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
elif [ -f "$HOME/.xprofile" ]; then
	. "$HOME/.xprofile"
fi

xrdb "${HOME}/.config/x11/xresources"
eval `ssh-agent`
exec dbus-launch --exit-with-session chadwm
