return {{
	mocha = {{
		rosewater = "{color4}",
		flamingo = "{color4}",
		red = "{color3}",
		maroon = "{color4}",
		pink = "{color5}",
		mauve = "{color5}",
		peach = "{color4}",
		yellow = "{color2}",
		green = "{color3}",
		teal = "{color6}",
		sky = "{color6}",
		sapphire = "{color6}",
		blue = "{color1}",
		lavender = "{color1}",
		text = "{foreground}",
		subtext1 = "{foreground}",
		subtext0 = "{color7}",
		overlay2 = "{color7}",
		overlay1 = "{color7}",
		overlay0 = "{color7}",
		surface2 = "{color7}",
		surface1 = "{foreground}",
		surface0 = "{background}",
		base = "{background}",
		mantle = "{background}",
		crust = "{background}",
	}},
}}
