#!/bin/bash

source "${HOME}/.cache/wal/colors.sh"

# mkdir -p  "${HOME}/.config/dunst"
# mkdir -p  "${HOME}/.config/zathura"
ln -sf    "${HOME}/.cache/wal/xresources"    "${HOME}/.config/x11/xresources"
xrdb "${HOME}/.config/x11/xresources"

sudo cp   "${HOME}/.cache/wal/vconsole.conf"    "/etc/vconsole.conf"
ln -sf    "${HOME}/.cache/wal/dunstrc"    "${HOME}/.config/dunst/dunstrc"
alpha=$(xrdb -query | grep "alpha" | cut -f 2)
sed -i -E "s/ALPHA/${alpha}/" "${HOME}/.cache/wal/zathurarc"
ln -sf    "${HOME}/.cache/wal/zathurarc"    "${HOME}/.config/zathura/zathurarc"
cp -uf     "${HOME}/.cache/wal/cava"    "${HOME}/.config/cava/config"
ln -sf    "${HOME}/.cache/wal/picom.conf"    "${HOME}/.config/picom.conf"
ln -sf    "${HOME}/.cache/wal/color_overrides.lua"    "${HOME}/.config/nvim/lua/color_overrides.lua"
# fix_sequences() {
#         e=$'\e'
#         sequences=$(cat)
#         foreground_color="$(echo -e "${sequences}\c" | grep --color=never -Eo "${e}]10[^${e}\\\\]*?${e}\\\\" | grep --color=never -Eo "#[0-9A-Fa-f]{6}")"
#         background_color="$(echo -e "${sequences}\c" | grep --color=never -Eo "${e}]11[^${e}\\\\]*?${e}\\\\" | grep --color=never -Eo "#[0-9A-Fa-f]{6}")"
#         cursor_color="$(echo -e "${sequences}\c" | grep --color=never -Eo "${e}]12[^${e}\\\\]*?${e}\\\\" | grep --color=never -Eo "#[0-9A-Fa-f]{6}")"
# }
# for term in /dev/pts/{0..9}*
# do
# echo -e "\e]4;256;${cursor_color}\a\c" > "${term}" 2>/dev/null
# echo -e "\e]4;258;${background_color}\a\c" > "${term}" 2>/dev/null
# echo -e "\e]4;259;${foreground_color}\a\c" > "${term}" 2>/dev/null
# done
# }

# fix_sequences <"${HOME}/.cache/wal/sequences"

pkill dunst; dunst &

pywalfox update
