#!/bin/bash

source "${HOME}/.cache/wal/colors.sh"

mkdir -p  "${HOME}/.config/dunst"
mkdir -p  "${HOME}/.config/zathura"
ln -sf    "${HOME}/.cache/wal/dunstrc"    "${HOME}/.config/dunst/dunstrc"
ln -sf    "${HOME}/.cache/wal/zathurarc"    "${HOME}/.config/zathura/zathurarc"
ln -sf    "${HOME}/.cache/wal/discord.scss"    "${HOME}/src/tty1/powercord/src/Powercord/themes/Comfy-git-clone/_custom.scss"
cp -uf     "${HOME}/.cache/wal/wal.vim"    "${HOME}/.config/nvim/autoload/lightline/colorscheme/wal.vim"
sed '/SHADER_COLORS/e cat $HOME/.cache/wal/shader' $HOME/.local/share/shader.og > $HOME/.local/share/shader.frag
rm -rf "${HOME}/docs/brave-pywal/Cached Theme.pak"
ln -sf    "${HOME}/.cache/wal/brave.json"    "${HOME}/docs/brave-pywal/manifest.json"
ln -sf    "${HOME}/.cache/wal/picom.conf"    "${HOME}/.config/picom.conf"
ln -sf    "${HOME}/.cache/wal/xresources"    "${HOME}/.config/x11/xresources"
xrdb "${HOME}/.config/x11/xresources"
wal -nR
fix_sequences() {
        e=$'\e'
        sequences=$(cat)
        foreground_color="$(echo -e "${sequences}\c" | grep --color=never -Eo "${e}]10[^${e}\\\\]*?${e}\\\\" | grep --color=never -Eo "#[0-9A-Fa-f]{6}")"
        background_color="$(echo -e "${sequences}\c" | grep --color=never -Eo "${e}]11[^${e}\\\\]*?${e}\\\\" | grep --color=never -Eo "#[0-9A-Fa-f]{6}")"
        cursor_color="$(echo -e "${sequences}\c" | grep --color=never -Eo "${e}]12[^${e}\\\\]*?${e}\\\\" | grep --color=never -Eo "#[0-9A-Fa-f]{6}")"

for term in /dev/pts/{0..9}*
do
echo -e "\e]4;256;${cursor_color}\a\c" > "${term}" 2>/dev/null
echo -e "\e]4;258;${background_color}\a\c" > "${term}" 2>/dev/null
echo -e "\e]4;259;${foreground_color}\a\c" > "${term}" 2>/dev/null
done
}

#fix_sequences <"${HOME}/.cache/wal/sequences"

pkill dunst; dunst &
